name: build github pages

on:
  push:
    branches:
    - main
jobs:
  build_pages:
    runs-on: ubuntu-18.04
    name: build github pages
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.BUILD_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
